/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.gradle.dependency.constrain;

import org.gradle.api.Plugin;
import org.gradle.api.initialization.Settings;
import org.gradle.api.model.ObjectFactory;
import org.gradle.dependency.constrain.lib.ConfigurationConstrainService;
import org.gradle.dependency.constrain.lib.ConstrainService;

import javax.inject.Inject;
import java.io.File;

/**
 * Plugin that applies dependency constraints to the build from an external configuration file.
 */
@SuppressWarnings("unused")
public abstract class GradleDependencyConstrainPlugin implements Plugin<Settings> {

    @Inject
    public abstract ObjectFactory getObjectFactory();

    public void apply(Settings settings) {
        ConfigurationConstrainService constraintService =
            ConstrainService.Factory
                .loadAndCreate(new File(settings.getRootDir(), "/gradle"))
                .create(settings.getBuildscript().getDependencies().getConstraints()::create);
        settings.getGradle().allprojects(project -> {
            constraintService.doConstrain(project.getBuildscript().getConfigurations());
            constraintService.doConstrain(project.getConfigurations());
        });
    }
}
